### ISSUE TITLE
Broken link to repository in npm package

### ISSUE THREAD

**Issue by frangio** [spalladino/hardhat-noir#1]
Clicking from https://www.npmjs.com/package/hardhat-noir to Repository lands at Page not found.

https://github.com/spalladino/hardhat-noir/blob/688bfd358b5475847ddd54616f9383e3d0bd26d8/package.json#L5

**Comment by spalladino** [comment]
Good catch! Fixed in df5d4c7d8ff64a1a02e685b3cb6815fa65581387.
